### ISSUE TITLE
Pdf-to-Text Conversion Not Possible Via FileUpload In-Browser for Mac

### ISSUE THREAD

**Issue by erhanyasar** [PDFTron/iOS-Getting-Started#1]
Well, you have presented your product as make in-browser pdf-rendering/pdf-converting  possible via javascript(?). However as you documented many features (it's not user friendly and not even targeting a user-experience) with your product, I could't reach my main object to use with your `API`.

My main object is to take a pdf file on web or mobile browser via Javascript's fileUpload property. As you declared with your documentation, it is definetely a subtle progress to be able to rendering `pdfs` client-side or browser-side unlike mainstream. Hence, through the API you provided there is no any option for the ones in my condition and I wanted to contribute here to attract a bit interest to your interface you may pay a more attention with it. 

I also send an e-mail and waiting for a return if it's provided via priced options or not but anyway, as a programmer and daily user interacting with many APIs it is really hard to understand if it is possible with your product or API.

**Comment by rbarrpdftron** [comment]
Thank you for the feedback, sorry if anything was confusing. If you have any specific feedback on something we can improve on please let me know.

Probably part of the confusion is that PDFTron actually offers a number of solutions. This repository is a guide for our native (C++/ObjC/Swift) [PDF SDK for iOS](https://www.pdftron.com/pdfnet/mobile/ios_pdf_library.html), and is not related to browsers directly. Though this SDK can view a PDF that is hosted remotely on a web server.

More likely you are interested in our [WebViewer](https://www.pdftron.com/webviewer/showcase/) solution, which allows for viewing of documents directly in any modern browser, on any modern device (desktop and mobile) with no plugins. WebViewer is pure HTML5, and fully customizable via HTML+CSS+JS.
https://www.pdftron.com/webviewer/index.html

You can download the WebViewer SDK and get started right away by downloading here.
https://www.pdftron.com/webviewer/download.html

**Comment by erhanyasar** [comment]
Very thanks for such a quick response either with mail and trial request respond. Sometimes teams are not organized and it takes days to take just an answer via a channel, so I used this way. Congrats for that.

Before touching my point, I just can suggest that you really need to revolutionize your `user interface`. As a both degree owner and having my carreer with reputation on both design and development, I just read your site for half an hour and still I couldn't be sure if I'm the only one who is struggling about it and in doubt if it has solution or not. (Mainly I can just suggest locating your products as a main object of your website and providing more simple way for a user reachable up to 3-4 clicks untill getting what he/she wants). I just wanted to add these as a friendly and open-hearted way, and I'd like to come to the real point unless your company would like to hire me for that (:

My main object is creating a webpage (mobil or web browser based) that let users add files `(image, text, doc/docx, and pdf)` through it. So I designed and developed an interface and algorithm at [erhanyasar.com.tr](http://erhanyasar.com.tr/portfolio/interface/file_upload/index.html) to display. I will take these all info via text and then send this text to some other service. So it's important to take these informations as text. Json either fits well but it's a bit though alternative I guess. Well, that's alright if user provides already text or it's not already hard to implement a library using OCR to transform image into text.

After I handled the core needs as I told upstairs, I started to dig more about pdf/docx to be able to use within my project. Till I saw your products, I ran into many other services making it server-side and it's not even to talk how revoloutionizing your product is as making this instead server-side. Hence, I'm still not interested in WebWiever or your SDK solutions in this case. I considered to be able to transform the pdf into text just in the meantime user user uploaded to the browser via javascript. But as I assume it's not technologically possible since yet (: I haven't ran into such an issue before and just faced yet even you serve different ways other than that. So, providing `WebWiever` and it's `textExtract` not the same things still with the information, APIs and samples you provided yet I guess.

I wrote both on mail and here to show the current situation to the future's possible seekers to be able find an answer if it's a product they are searching for already and even maybe encourage you to add this attribute. Or maybe influencing someone looking here to build a tool to handle that. To be short, I couldn't able to make it work as I tried to explain in my case within your API. Please approve me if it's not possible either or if I'm the one not succeeded to implement to my case. Either both way, you have something to develop your current product or I have a product idea to not have a solution yet.

Well, thanks anyway and you may close if you feel it's not possible yet. I'll be probably taking a look at more closely about it.

**Comment by rbarrpdftron** [comment]
Thank you for the additional feedback.

As for your project, and I know you already filed in a Mobile Evaluation form, but there was not much information there. I would suggest filling out one of the following forms, and please describe your requirements in more detail. In particular document work flow, step-by-step.
https://www.pdftron.com/support/presales.html
https://www.pdftron.com/licensing/quote.html

As mentioned we have a number of different solutions, but need a clearer picture of your project to provide the best options, and github issue tracker is not the ideal place for this sort of conversation.

**Comment by erhanyasar** [comment]
Well, after a long research before issuing a file here, I thought it's possibly not probable that your product either not able to do the exact case and then I issued it as a missing feature or something more than product support. You may free to close as I'm sending my further request with the links you provided. Or you may do that after our conversation concluded via mail and you may want to display the result that your product is or is not able to achieve that by itself already.
